export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-']

export const URGENCY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  NORMAL: 'NORMAL',
}

export const REQUEST_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
}

export const PLEDGE_STATUS = {
  ACCEPTED: 'ACCEPTED',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  VOID: 'VOID',
}

export const DONATION_STATE = {
  RECORDED: 'RECORDED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
}

export const DONATION_TYPE = {
  WHOLE_BLOOD: 'WHOLE_BLOOD',
  PLASMA: 'PLASMA',
  PLATELETS: 'PLATELETS',
}

export const DONOR_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RECOVERING: 'RECOVERING',
  UNAVAILABLE: 'UNAVAILABLE',
  INELIGIBLE: 'INELIGIBLE',
}

export const PLEDGE_CANCEL = {
  SCHEDULE_CONFLICT: 'SCHEDULE_CONFLICT',
  HEALTH: 'HEALTH',
  DISTANCE: 'DISTANCE',
  REQUEST_FULFILLED: 'REQUEST_FULFILLED',
  OTHER: 'OTHER',
}

export const REQUEST_REJECT = {
  INVALID_PROOF: 'INVALID_PROOF',
  DUPLICATE: 'DUPLICATE',
  UNREACHABLE: 'UNREACHABLE',
  OTHER: 'OTHER',
}

export const AVAILABILITY_PREFERENCE = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
}

export const ACCOUNT_TYPE = {
  USER: 'user',
  HOSPITAL: 'hospital',
}
